### ISSUE TITLE
Allow A-Z to work with Created By meta field.

### ISSUE THREAD

**Issue by rafaehlers** [GravityKit/AZ-Filters#34]
So the user can click on the letter and only display entries with that user's Display Name (the entry creator).

**Comment by rafaehlers** [comment]
https://secure.helpscout.net/conversation/589620972/14934

**Comment by mrcasual** [comment]
@rafaehlers, this was released in v1.4:

`* Support for filtering entries using the "Created By" field.`

Please notify the customer (although the ticket is from 2018 :)) and/or close the issue.

**Comment by rafaehlers** [comment]
No longer a customer... 😢
