### ISSUE TITLE
Add Greek Alphabet Support

### ISSUE THREAD

**Issue by bennemann** [GravityKit/AZ-Filters#48]
```
add_filter( 'gravityview_az_entry_filter_localization', function( $languages = array() ) {
	$languages['el_GR'] = __( 'Greek', 'gravityview-az-filters' );
	return $languages;
});

add_filter( 'gravityview_alphabets', function( $alphabet = array() ) {
	$alphabet['el_GR'] = array('α', 'ά', 'β', 'γ', 'δ', 'ε', 'έ', 'ζ', 'η', 'ή', 'θ', 'ι', 'ί', 'κ', 'λ', 'μ', 'ν', 'ξ', 'ο', 'ό', 'π', 'ρ', 'σ', 'τ', 'υ', 'ύ', 'φ', 'χ', 'ψ', 'ω', 'ώ');
	return $alphabet;
});
```

**Comment by bennemann** [comment]
https://secure.helpscout.net/conversation/2032742288/44050/

**Comment by rafaehlers** [comment]
@bennemann already committed this code:  https://github.com/GravityKit/AZ-Filters/releases/tag/v1.3.4

https://github.com/GravityKit/AZ-Filters/blob/e52b57d71d25d94fb9a76c8fff85424e56d110d9/widget/gravityview-a-z-entry-filter-widget.php#L174
https://github.com/GravityKit/AZ-Filters/blob/e52b57d71d25d94fb9a76c8fff85424e56d110d9/widget/gravityview-a-z-entry-filter-widget.php#L546
